version: '3.8'

services:
  be-kakaon:
    build: ./be-kakaon
    container_name: be-kakaon
    restart: always
    env_file:
      - be-kakaon/.env
    ports:
      - "8083:8080"
    networks:
      - my-proxy-net

  fe-kakaon:
    build: ./fe-kakaon
    container_name: fe-kakaon
    restart: always
    env_file:
      - fe-kakaon/.env
    ports:
      - "3001:80"
    networks:
      - my-proxy-net
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - my-proxy-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external: true
