version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "${JENKINS_PORT}:50000"
    environment:
      - TZ=Asia/Seoul
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - /home/ubuntu/jenkins-data:/var/jenkins_home
      - /home/ubuntu/app:/home/ubuntu/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend-net

  nginx-jenkins:  
    image: nginx:alpine
    container_name: nginx-jenkins
    restart: always
    ports:
      - "${NGINX_JENKINS_PORT}:443"
    volumes:
      - ./nginx-jenkins.conf:/etc/nginx/conf.d/default.conf:ro
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - jenkins
    networks:
      - backend-net

  be-kakaon:
    build: ./be-kakaon
    container_name: be-kakaon
    restart: always
    env_file:
      - ./.env
      - ./be-kakaon/.env
    ports:
      - "${SPRING_PORT}:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend-net

  mysql:
    image: mysql:8.0.37
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$MYSQL_USER -p$MYSQL_PASSWORD"]
      interval: 5s
      retries: 10

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10

  fe-kakaon:
    build: ./fe-kakaon
    container_name: fe-kakaon
    restart: always
    env_file:
      - ./.env
      - ./fe-kakaon/.env
    ports:
      - "${FE_HTTP_PORT}:80"
      - "${FE_HTTPS_PORT}:443"
    depends_on:
      - be-kakaon
    networks:
      - backend-net
    volumes:
      # 배포용 HTTPS conf로 덮어쓰기
      - ./fe-kakaon/nginx/nginx.https.conf:/etc/nginx/conf.d/default.conf:ro
      # 인증서/챌린지 파일 공유
      - letsencrypt:/etc/letsencrypt
      - certbot-web:/var/www/certbot
  
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-web:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    networks: [backend-net]

volumes:
  mysql_data:
  redis_data:
  letsencrypt:
  certbot-web:

networks:
  backend-net:
    driver: bridge
